spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/interview?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456

  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: simon # Redis服务器连接密码（默认为空）

aliyun:
  oss:
    accessKeyId: 
    accessKeySecret: 
    endpoint: oss-cn-shenzhen.aliyuncs.com
    bucket-name: fty-oos
    callbackUrl: http://127.0.0.1:8081
    expireTime: 30
    dir-prefix: interview/

swagger:
  enable: true #是否开启swagger
springfox:
  documentation:
    swagger:
      v2:
        enabled: false #是否开启swagger文档base url